# -*- coding: utf-8 -*-
"""
Created on Wed Apr 24 14:56:08 2024

@author: mastadle
"""
import xml.etree.ElementTree as ET
import argparse
from tkinter import Tk

parser = argparse.ArgumentParser(
        prog="CleanSVG",
        description=(
            "Clean the SVG generated by plotly for gneral use.\n"
            "If only one argument is specified it will try to read from clipboard"
            )
        )

parser.add_argument('inputFilename', nargs='?', default='clipboard')
parser.add_argument('outputFilename', nargs='?', default='output.svg')

args = parser.parse_args()
if args.inputFilename == "clipboard":
    w = Tk()
    clipboard = w.clipboard_get();
    w.destroy()
    root = ET.fromstring(clipboard)
else:
    tree = ET.parse(args.inputFilename)
    root = tree.getroot()

ns = {
      "svg": "http://www.w3.org/2000/svg"
      }
for elem in root.iter():
    if elem.tag[-1] == "g":
        for rect in elem.findall("svg:rect", ns):
            if "style" in rect.attrib:
                # Remove all transparent ractangles
                if ("fill: transparent" in rect.attrib["style"] or
                    "fill: rgba(0,0,0,0)" in rect.attrib["style"]):
                    elem.remove(rect)

svgs = root.findall("svg:svg", ns)
svg = svgs[1]
for elem in svg:
    # Merge SVGs
    svgs[0].extend(elem)

svgs[0].attrib.pop("style")

timeElements = []

for elem in svgs[0].iter():
    if "style" in elem.attrib and "pointer-events" in elem.attrib["style"]:
        # Remove pointer-events that inkscape coplains about
        elem.attrib.pop("style")

    if "style" in elem.attrib:
        elem.attrib["style"] = elem.attrib["style"].replace('"Open Sans"', "Charter")
    # Enable if inkscapelatex is true
    if elem.text:
        # Enable for latex
        if False:
            # long dash
            elem.text = elem.text.replace("\u2212", "--")
            # Mu
            elem.text = elem.text.replace("\u03bcs", r"\unit{\micro\s}")
            for title in ("f / MHz", "p / °", "a / %"):
                elem.text = elem.text.replace(title, f"\\smaller{{}}{title}\\larger{{}}")
        else:
            idx = elem.text.find("\u03bcs")
            if idx >= 0:
                elem.text = elem.text[:idx]
                timeElements.append(elem)

for time in timeElements:
    unit = ET.SubElement(time, 'svg:tspan')
    unit.set('style', "font-family:'Latin Modern Math'")
    unit.text = "\u03bcs"



svgOutput = ET.ElementTree(element=svgs[0])
ET.indent(svgOutput, space="  ", level=0)
svgOutput.write(args.outputFilename)
        
