services:
  visualizer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${VISUALIZER_PORT:-8080}:80"

  sequence_server:
    profiles: [sequence_server]
    build:
      context: ./test
      dockerfile: Dockerfile
    ports:
      - "${SEQUENCE_SERVER_PORT:-8003}:8003"
    volumes:
      - ${SEQUENCE_FILE}:/data/sequence.json:ro
      - ${HARDWARE_FILE}:/data/hardware.json:ro
