#!/bin/sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

stash_commit="$(git stash create)"

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

status=$?

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

if [[ -n "${stash_commit}" ]]; then
  git stash apply "${stash_commit}"
fi

exit $status
