import { useImmer } from "use-immer";
import { SequenceVisualiser } from "./SequenceVisualiser";

import { SequenceParser } from "./SequenceParser.js";
import { ConnectionStatus } from "./ConnectionStatus";
import { Modal, Spinner, Button } from "react-bootstrap";
import { useNavigate } from "react-router";
import { isEmbedded } from "./embeddedMode";

/**
 * @param {Object} channelDescription description for each visual channel as returned by the experiment library
 *                    The Object maps from the visual channel
 * @param {Object} ionpulseSequence Object created from the sequence JSON generated by the ionpulse sequence generator
 */
const IonpulseSequenceVisualiser = function IonpulseSequenceVisualiser({
  channelDescription,
  ionpulseSequence,
  connectionStatus,
  connectionErrMsg,
}) {
  const [sequenceConfig, setSequenceConfig] = useImmer({});

  // TODO: Use function instead of Object
  let sequenceParser = new SequenceParser(ionpulseSequence, sequenceConfig);

  function updateSequenceConfig(recipe) {
    setSequenceConfig(recipe);
  }
  const navigate = useNavigate();

  return (
    <>
      <Modal
        show={connectionStatus !== ConnectionStatus.connected}
        backdrop="static"
        keyboard={false}
      >
        <Modal.Header>
          <Modal.Title>
            {connectionStatus === ConnectionStatus.failed ? (
              <span className="text-danger">Failed to connect to library</span>
            ) : (
              "Connecting to library"
            )}
          </Modal.Title>
        </Modal.Header>

        <Modal.Body className="text-center">
          {connectionStatus === ConnectionStatus.connecting ? (
            <Spinner className="m-3" animation="border" role="status">
              <span className="visually-hidden">Loading...</span>
            </Spinner>
          ) : (
            <span>{connectionErrMsg}</span>
          )}
        </Modal.Body>

        {!isEmbedded && (
          <Modal.Footer>
            <Button
              variant="primary"
              onClick={() => {
                navigate("/config");
              }}
            >
              Go to configuration
            </Button>
          </Modal.Footer>
        )}
      </Modal>
      <SequenceVisualiser
        channelDescription={channelDescription}
        pulseSequenceData={sequenceParser.plotData}
        sequenceBlockData={sequenceParser.sequenceBlockData}
        sequenceConfig={sequenceConfig}
        setSequenceConfig={updateSequenceConfig}
      />
    </>
  );
};

export { IonpulseSequenceVisualiser };
